### ISSUE TITLE
Unable to disconnect

### ISSUE THREAD

**Issue by YoHidden** [ARMmbed/cordio-ble-x-nucleo-idb0xa1#5]
Hi there,

I'm testing this library with the GattClient example provided at [mbed-os-example-ble](https://github.com/ARMmbed/mbed-os-example-ble). I have slightly modified the example just to avoid the initial advertising process and directly scan for my device and connect to it. It works ok and every service, characteristic and descriptor is being shown.

**But**, I have also added a disconnection request when all characteristics discovered have been processed. At that point, I call the _disconnect()_ function but got an error code 2, which is BLE_ERROR_NOT_IMPLEMENTED. I have tried both calls to ble interface object an to its gap() object inside it. Same result always.

Am I following the right way to disconnect from the peripheral ?

Thanks.

**Comment by pan-** [comment]
Hi @YoHidden . 

Please make sure to call the disconnect overload that accepts the connection and the disconnection reason: `disconnect(connection, reason)`. The overload that just accepts the reason: `disconnect(reason)` is deprecated and not implemented by the Gap implementation used by this driver.

**Comment by YoHidden** [comment]
Hi @pan- 

Ok, I was using the overload with only the reason argument. I'll give it a try as soon as I am back to the lab, but I'm pretty sure that was the problem.

Thanks @pan- .
