### ISSUE TITLE
HCI compatibility with BlueNRG-2 

### ISSUE THREAD

**Issue by ladislas** [ARMmbed/cordio-ble-x-nucleo-idb0xa1#9]
Hi there!

I'm wondering if the HCI implementation could be compatible with BlueNRG-M2 (using BlueNRG-2).

I'm willing to make the port but I'm not sure where to start.

Thanks a lot!
Ladislas

**Comment by jeromecoutant** [comment]
@ARMmbed/team-st-ble 
Please give some advice
Thx

@LMESTM

**Comment by ladislas** [comment]
This was answered in https://github.com/ARMmbed/mbed-os/pull/12456 -- closing the issue :)
